export const collections = [
  { name: 'Bad Bunny' },
  { name: 'Shakira' },
  { name: 'Money Heist' },
];

export const decks = [
  {
    name: 'Bad Bunny - Vete',
    num_cards: '35',
    img: 'https://picsum.photos/200/300',
    cards: [
      { front: 'hola', back: 'hello' },
      { front: 'hola', back: 'hello' },
      { front: 'hola', back: 'hello' },
      { front: 'hola', back: 'hello' },
      { front: 'hola', back: 'hello' },
      { front: 'hola', back: 'hello' },
      { front: 'hola', back: 'hello' },
      { front: 'hola', back: 'hello' },
      { front: 'hola', back: 'hello' },
      { front: 'hola', back: 'hello' },
      { front: 'hola', back: 'hello' },
      { front: 'hola', back: 'hello' },
      { front: 'hola', back: 'hello' },
      { front: 'hola', back: 'hello' },
      { front: 'hola', back: 'hello' },
      { front: 'hola', back: 'hello' },
      { front: 'hola', back: 'hello' },
      { front: 'hola', back: 'hello' },
      { front: 'hola', back: 'hello' },
    ],
  },
  {
    name: 'Shakira - Chantaje',
    num_cards: '39',
    img: 'https://picsum.photos/200/300',
    cards: {
      1: { front: 'hola', back: 'hello' },
      2: { front: 'hola', back: 'hello' },
      3: { front: 'hola', back: 'hello' },
      4: { front: 'hola', back: 'hello' },
      5: { front: 'hola', back: 'hello' },
      6: { front: 'hola', back: 'hello' },
      7: { front: 'hola', back: 'hello' },
      8: { front: 'hola', back: 'hello' },
      9: { front: 'hola', back: 'hello' },
    },
  },
  {
    name: 'Shakira - Me Gusta',
    num_cards: '28',
    img: 'https://picsum.photos/200/300',
    cards: {
      1: { front: 'hola', back: 'hello' },
      2: { front: 'hola', back: 'hello' },
      3: { front: 'hola', back: 'hello' },
      4: { front: 'hola', back: 'hello' },
      5: { front: 'hola', back: 'hello' },
      6: { front: 'hola', back: 'hello' },
      7: { front: 'hola', back: 'hello' },
      8: { front: 'hola', back: 'hello' },
      9: { front: 'hola', back: 'hello' },
    },
  },
  {
    name: 'Shakira - Bicicleta',
    num_cards: '35',
    img: 'https://picsum.photos/200/300',
    cards: {
      1: { front: 'hola', back: 'hello' },
      2: { front: 'hola', back: 'hello' },
      3: { front: 'hola', back: 'hello' },
      4: { front: 'hola', back: 'hello' },
      5: { front: 'hola', back: 'hello' },
      6: { front: 'hola', back: 'hello' },
      7: { front: 'hola', back: 'hello' },
      8: { front: 'hola', back: 'hello' },
      9: { front: 'hola', back: 'hello' },
    },
  },
  {
    name: `Shakira - Hips Don't Lie`,
    num_cards: '31',
    img: 'https://picsum.photos/200/300',
    cards: {
      1: { front: 'hola', back: 'hello' },
      2: { front: 'hola', back: 'hello' },
      3: { front: 'hola', back: 'hello' },
      4: { front: 'hola', back: 'hello' },
      5: { front: 'hola', back: 'hello' },
      6: { front: 'hola', back: 'hello' },
      7: { front: 'hola', back: 'hello' },
      8: { front: 'hola', back: 'hello' },
      9: { front: 'hola', back: 'hello' },
    },
  },
];

export const recommendations = [
  {
    name: 'Bad Bunny - P FKN R',
    cards: '35',
    img: 'https://picsum.photos/200/300',
  },
  { name: 'Shakira - Nada', cards: '39', img: 'https://picsum.photos/200/300' },
  {
    name: 'Shakira - Amarillo',
    cards: '28',
    img: 'https://picsum.photos/200/300',
  },
  {
    name: 'Shakira - Deja Vu',
    cards: '35',
    img: 'https://picsum.photos/200/300',
  },
  {
    name: `Shakira - What We Said`,
    cards: '31',
    img: 'https://picsum.photos/200/300',
  },
];
