export const collections = [
  { name: 'Bad Bunny' },
  { name: 'Shakira' },
  { name: 'Money Heist' },
];

export const decks = [
  {
    name: 'Bad Bunny - Estamos Bien',
    num_cards: '35',
    img: 'https://picsum.photos/200/300',
    cards: [
      { front: "'Tamos bien", back: "We're good" },
      {
        front: 'Sobran los billetes de cien',
        back: 'Surplus of one hundred (dollar) bills',
      },
      { front: "To' los mío' están bien", back: 'All my people are good' },
      { front: 'No hay nada mal', back: "There's nothing wrong" },
      { front: 'El dinero', back: 'Money' },
      { front: 'Me llueve', back: 'It rains on me' },
      { front: 'Diablo qué aguacero', back: 'Dude what a downpour' },
      { front: 'En la cuenta', back: 'In the account' },
      { front: "Empezamo' desde cero", back: 'We start from zero' },
      { front: 'Soy un grosero', back: 'I am a rude person' },
      { front: 'Que se joda', back: 'Fuck it' },
      { front: 'Soy sincero', back: 'I am sincere' },
      { front: "Ya estoy acostumbra'o", back: "I'm already used to" },
      { front: 'El cielo', back: 'The sky' },
      { front: 'Vuelo privado', back: 'I fly privado' },
      { front: 'Gasto y no me pelo', back: "I spend and I don't run out" },
      { front: "Mucha' puta' y modelo'", back: 'Many bitches and models' },
      { front: 'Me levanté contento', back: 'I wake up content' },
      { front: 'Aunque', back: 'Even though' },
    ],
  },
  {
    name: 'Shakira - Chantaje',
    num_cards: '39',
    img: 'https://picsum.photos/200/300',
    cards: {
      1: { front: 'hola', back: 'hello' },
      2: { front: 'hola', back: 'hello' },
      3: { front: 'hola', back: 'hello' },
      4: { front: 'hola', back: 'hello' },
      5: { front: 'hola', back: 'hello' },
      6: { front: 'hola', back: 'hello' },
      7: { front: 'hola', back: 'hello' },
      8: { front: 'hola', back: 'hello' },
      9: { front: 'hola', back: 'hello' },
    },
  },
  {
    name: 'Shakira - Me Gusta',
    num_cards: '28',
    img: 'https://picsum.photos/200/300',
    cards: {
      1: { front: 'hola', back: 'hello' },
      2: { front: 'hola', back: 'hello' },
      3: { front: 'hola', back: 'hello' },
      4: { front: 'hola', back: 'hello' },
      5: { front: 'hola', back: 'hello' },
      6: { front: 'hola', back: 'hello' },
      7: { front: 'hola', back: 'hello' },
      8: { front: 'hola', back: 'hello' },
      9: { front: 'hola', back: 'hello' },
    },
  },
  {
    name: 'Shakira - Bicicleta',
    num_cards: '35',
    img: 'https://picsum.photos/200/300',
    cards: {
      1: { front: 'hola', back: 'hello' },
      2: { front: 'hola', back: 'hello' },
      3: { front: 'hola', back: 'hello' },
      4: { front: 'hola', back: 'hello' },
      5: { front: 'hola', back: 'hello' },
      6: { front: 'hola', back: 'hello' },
      7: { front: 'hola', back: 'hello' },
      8: { front: 'hola', back: 'hello' },
      9: { front: 'hola', back: 'hello' },
    },
  },
  {
    name: `Shakira - Hips Don't Lie`,
    num_cards: '31',
    img: 'https://picsum.photos/200/300',
    cards: {
      1: { front: 'hola', back: 'hello' },
      2: { front: 'hola', back: 'hello' },
      3: { front: 'hola', back: 'hello' },
      4: { front: 'hola', back: 'hello' },
      5: { front: 'hola', back: 'hello' },
      6: { front: 'hola', back: 'hello' },
      7: { front: 'hola', back: 'hello' },
      8: { front: 'hola', back: 'hello' },
      9: { front: 'hola', back: 'hello' },
    },
  },
];

export const recommendations = [
  {
    name: 'Bad Bunny - P FKN R',
    cards: '35',
    img: 'https://picsum.photos/200/300',
  },
  { name: 'Shakira - Nada', cards: '39', img: 'https://picsum.photos/200/300' },
  {
    name: 'Shakira - Amarillo',
    cards: '28',
    img: 'https://picsum.photos/200/300',
  },
  {
    name: 'Shakira - Deja Vu',
    cards: '35',
    img: 'https://picsum.photos/200/300',
  },
  {
    name: `Shakira - What We Said`,
    cards: '31',
    img: 'https://picsum.photos/200/300',
  },
];
